version: "3.8"

services:
  expo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expo-app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "19000:19000" # Expo client
      - "19001:19001" # Metro bundler
      - "19002:19002" # Expo DevTools
      - "8081:8081" # React Native packager
    environment:
      - NODE_ENV=development
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    command: npm start -- --host=0.0.0.0

volumes:
  node_modules:
